### ISSUE TITLE
Bug in testcode in main.cpp

### ISSUE THREAD

**Issue by DominicD** [NatWeiss/EntityFu#6]
When I run the main.cpp I get an Assertion:
vector iterator not incrementable

It happens after Entity 2 gets to 0 health and gets destroyed.

I could fix it by changing this: 

```
for (auto eid : Entity::getAll<HealthComponent>())
```

to this:

```
auto vec = Entity::getAll<HealthComponent>();
for (auto eid : vec)
```

**Comment by NatWeiss** [comment]
Thanks so much! I incorporated your fix into the repo with some comment explanation and a faster alternative.
